version: "3.8"
services:
  # client:
  #   build: ./mobi-context-tracking-fe/
  server:
    build: .
    ports:
      - "5000:3090"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=mobi_tracking_db
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mobi-context-tracking-be/db-scripts:/docker-entrypoint-initdb.d
      - mysql-db:/data/db
    restart: always
    healthcheck:
      test: mysql --user=$$MYSQL_ROOT_USER --password=$$MYSQL_ROOT_PASSWORD -e 'SHOW DATABASES;'
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 15s
volumes:
  mysql-db:
